name: Publish Workflow
'on':
  workflow_run:
    workflows:
    - Release Workflow
    - Create Release
    types:
    - completed
jobs:
  publish:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@main
    - name: Setup Git
      uses: actions/setup-python@v6
      with:
        python-version: 3.x
      run: git config --global user.email "github-actions[bot]@users.noreply.github.com"
        && git config --global user.name "github-actions[bot]"
    - name: Setup Python
      run: curl -sSL https://install.python-poetry.org | python3 -
      uses: actions/setup-python@main
      with:
        python-version: 3.x
    - name: Install Poetry
      run: curl -sSL https://install.python-poetry.org | python3 -
    - name: Configure Poetry
      run: poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}
    - name: Build and publish to PyPI
      run: poetry publish --build
permissions:
  contents: read
run-name: Publish Workflow
